install antigen
install curl
install exa
install fzy
install git
install httpie
install hub
install jq
install neovim
install python
install python3
install rbenv
install readline
install the_silver_searcher
install vim
install wget
install zsh
install zsh-completions
