#!/usr/bin/env bash
###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################



export NB_HEADER="${NB_HEADER:-1}" # Set by `nb` • Fri Oct 23 00:15:19 CEST 2020

export NB_SYNTAX_THEME="${NB_SYNTAX_THEME:-Monokai Extended Bright}" # Set by `nb` • Fri Oct 23 00:17:59 CEST 2020

export NB_COLOR_THEME="${NB_COLOR_THEME:-utility}" # Set by `nb` • Fri Oct 23 00:22:11 CEST 2020

export NB_FOOTER="${NB_FOOTER:-0}" # Set by `nb` • Fri Oct 23 13:21:34 CEST 2020
