[plugins.zsh-async]
github = "mafredri/zsh-async"

[plugins.promptinit]
inline = "autoload -U promptinit; promptinit"

[plugins.syntax-highlighting]
github="zdharma/fast-syntax-highlighting"

[plugins.history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.history-fzy]
gist = "shogogg/86f13a0aff12b9a31efb083946a500cb"

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.asdf]
local = "/usr/local/opt/asdf/lib"
use = ["asdf.sh"]
apply = ["source"]

[plugins.docker]
github = "robbyrussell/oh-my-zsh"
dir = "plugins/{{ name }}"
apply = ["fpath"]

[plugins.docker-compose]
github = "robbyrussell/oh-my-zsh"
dir = "plugins/{{ name }}"
apply = ["source", "fpath"]

# update completions
[plugins.compinit]
inline = "compinit"

# Load local plugins last, so they can overwrite config
[plugins.dotfiles]
local = "~/.zsh"

[plugins.brew-completions]
local = "/usr/local/etc/bash_completion.d"
apply = ["fpath"]

# [plugins.rust]
# local = "~/.rustup/toolchains/stable-*/share/zsh/site-functions"
# apply = ["fpath"]

# [plugins.wd]
# github = "mfaerevaag/wd"
# tag = "v0.4.6"
# apply = ["alias", "fpath"]

# [plugins.zsh-autosuggestions]
# github = "zsh-users/zsh-autosuggestions"
# tag = "v0.5.2"
# use = ["{{ name }}.zsh"]


# [plugins.git]
# github = "robbyrussell/oh-my-zsh"
# directory = "plugins/{{ name }}"
