format = """
[┌──────────────────────────────────────────────────────────────────────────────](bold bright-blue)
[│](bold bright-blue) \
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration
[└─$jobs$character](bold bright-blue)"""

[jobs]
disabled = false
symbol = "+"
threshold = 1
format = "[|$symbol$number|─](bold bright-blue)"

[git_branch]
style = "bold green"
