#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
# shellcheck source=./lib/messaging.sh
source "${SCRIPT_DIR}/lib/messaging.sh"

CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}
CONFIG_FILE="${CONFIG_DIR}/dotfiles.cfg"

# utils

fn_exists () {
    declare -F "$1" > /dev/null
}

file_contains () {
    local file=$1
    local search=$2

    if grep -q "$search" "$file"; then
        return 0
    else
        return 1
    fi
}

# main

bootstrap () {
    cd "$(dirname "$0")/.."
    bootstrap_colors
    msg_header "==> script/bootstrap"

    bootstrap_config
    bootstrap_app_store
    bootstrap_secure_dir
    bootstrap_shell
    bootstrap_xcode
    bootstrap_homebrew
}

bootstrap_config () {
    if [ -f "${CONFIG_FILE}" ]; then return; fi

    msg_info "==> Initializing config"

    mkdir -p "$(dirname "${CONFIG_FILE}")"
    touch "${CONFIG_FILE}"
}

bootstrap_app_store () {
    local skip
    skip=$(config_get skip_bootstrap_app_store 0)

    if [ "${skip}" == "1" ]; then return; fi

    affirm "Have you authenticated with the App Store?"
    config_set skip_bootstrap_app_store 1
}

bootstrap_secure_dir () {
    local skip
    skip=$(config_get skip_bootstrap_secure_dir 0)

    if [ "${skip}" == "1" ]; then return; fi

    local dir

    configure secure_dir \
        "Where do you store secure files?" \
        "${HOME}/Library/Mobile Documents/com~apple~CloudDocs/dotfiles"
    dir=$(config_get secure_dir)

    affirm "Have you downloaded secure files to ${dir}?"
    config_set skip_bootstrap_secure_dir 1
}

bootstrap_shell () {
    local skip
    skip=$(config_get skip_bootstrap_shell 0)

    if [ "${skip}" == "1" ]; then return; fi

    configure shell_bin \
        "What is the path to your preferred shell?" \
        "/usr/local/bin/zsh"
    config_set skip_bootstrap_shell 1
}

# config

configure () {
    local key=$1
    local prompt=$2
    local default=$3
    local current

    # check if already configured
    current=$(config_get "${key}" "__UNDEFINED__")
    if [ "${current}" != "__UNDEFINED__" ]; then return; fi

    msg_warn "\n${prompt}"
    read -e -r -p "[${default}]: "

    if [[ $REPLY == "" ]]; then
        config_set "${key}" "${default}"
    else
        config_set "${key}" "${REPLY}"
    fi
}

config_get() {
    local key=$1

    local value
    value=$(
        (grep -E "^${key}=" -m 1 "${CONFIG_FILE}" 2>/dev/null || echo "VAR=__UNDEFINED__") \
            | head -n 1 \
            | cut -d '=' -f 2-)

    if [ "${value}" = "__UNDEFINED__" ]; then
        # errors if no default provided
        value="${2}"
    fi
    printf -- "%s" "${value}"
}

config_set() {
    local key=$1
    local value=$2

    grep -q "^${key}" "${CONFIG_FILE}" && \
        sed -i "" "s'^${key}=.*'${key}=${value}'" "${CONFIG_FILE}" \
        || echo "${key}=${value}" >> "${CONFIG_FILE}"
}

bootstrap_xcode () {
    msg_info "==> Looking for Command Line Tools"
    xcode-select --print-path >/dev/null 2>&1 || {
        msg_info "==> Installing Command Line Tools"
        xcode-select --install
    }
}

bootstrap_homebrew () {
    if ! [ -x "$(command -v brew)" ]; then
        msg_info "==> Installing Homebrew"
        /usr/bin/env bash -c \
            "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
        if [ ! -e "$HOME/.Brewfile" ]; then
            msg_info "==> Symlinking Brewfile to ~/.Brewfile"
            ln -s "${SCRIPT_DIR}/../Brewfile" "$HOME/.Brewfile"
        fi
        msg_info "==> Installing Homebrew dependencies"
        script/brew-bundle-interactive
    fi
}

if ! (return 0 2>/dev/null); then
    bootstrap "$@"
fi
