#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies

set -euo pipefail
IFS=$'\n\t'

bootstrap () {
    cd "$(dirname "$0")/.."
    msg_header "==> script/bootstrap…"

    bootstrap_xcode
    bootstrap_homebrew
}

bootstrap_xcode () {
    msg_info "==> Looking for Command Line Tools…"
    xcode-select --print-path >/dev/null 2>&1 || {
        msg_info "==> Installing Command Line Tools…"
        xcode-select --install
    }
}

bootstrap_homebrew () {
    if ! [ -x "$(command -v brew)" ]; then
        msg_info "==> Installing Homebrew…"
        /usr/bin/env bash -c \
            "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi
    if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
        msg_info "==> Checking Homebrew dependencies…"
        brew bundle check >/dev/null 2>&1  || {
            msg_info "==> Installing Homebrew dependencies…"
            brew bundle --no-upgrade
        }
    fi
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
    script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
    # shellcheck source=./install
    source "${script_dir}/install"
    setup_colors
    bootstrap "$@"
fi
