#!/usr/bin/env bash

# script/install: Clone repository and execute setup

set -euo pipefail
IFS=$'\n\t'

trap cleanup SIGINT SIGTERM ERR EXIT

REPO="https://github.com/jackboberg/dotfiles.git"
SRC_DIR="${HOME}/src/github.com/jackboberg"
DOT_DIR="${SRC_DIR}/dotfiles"

install () {
    msg_header "==> script/install…"
    install_xcode
    get_dotfiles
    setup
}

cleanup () {
    trap - SIGINT SIGTERM ERR EXIT
    msg_info "==> Cleaning up…"
}

setup_colors () {
    if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
        NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
    else
      NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
    fi
}

msg () {
    echo >&2 -e "${1-}"
}

msg_info () {
    msg "${PURPLE}${1-}${NOFORMAT}"
}

msg_header () {
    msg "${BLUE}${1-}${NOFORMAT}"
}

install_xcode () {
    msg_info "==> Looking for Command Line Tools…"
    xcode-select --print-path >/dev/null 2>&1 || {
        msg_info "==> Installing Command Line Tools…"
        xcode-select --install
    }
}

get_dotfiles () {
    msg_info "==> Getting dotfiles…"
    if [ -d "$DOT_DIR" ]; then
        msg_info "==> $DOT_DIR exists…"
        exit 1
    fi

    mkdir -p $SRC_DIR
    git clone $REPO $DOT_DIR
}

setup () {
    msg_info "==> Setting up dotfiles…"
    cd $DOT_DIR
    script/setup
}

setup_colors

if \
  [ "$0##*/}" == "bash" ] || \
  [ "${0}" == "/dev/fd/11" ] || \
  [ "${#BASH_SOURCE[@]}" -eq 1 ]
then
    install "$@"
fi
