#!/usr/bin/env bash

# script/setup: Set up system for the first time after cloning

set -euo pipefail
IFS=$'\n\t'

setup () {
    cd "$(dirname "$0")/.."
    affirm "Have you authenticated with the App Store?"

    script/bootstrap
    msg_header "==> script/setup…"

    setup_rc
    setup_secure_files
    setup_iterm
    setup_emacs
    setup_asdf
}

setup_rc () {
    msg_info "==> Setting up RC files…"
    local dir

    # Set this repo as the source directory.
    dir=$(pwd)
    echo "DOTFILES_DIRS=\"${dir}\"" >> ./rcrc

    env RCRC=${dir}/rcrc rcup
}

setup_secure_files () {
    msg_info "==> Setting up secure files…"
    local icloud_dir
    icloud_dir="${HOME}/Library/Mobile\ Documents/com\~apple\~CloudDocs"

    # symbolically link private git config
    ln -s "${icloud_dir}/gitconfig.local" ~/.gitconfig.local

    # symbolically link private zsh config
    ln -s "${icloud_dir}/rc.local" ~/.localrc
}

setup_iterm () {
    msg_info "==> Setting up iTerm2 preferences…"
    local dir
    local plist
    plist="com.googlecode.iterm2.plist"

    # Specify the preferences directory
    dir="$(pwd)/iTerm2"
    defaults write "${plist}" PrefsCustomFolder -string "${dir}"

    # Tell iTerm2 to use the custom preferences in the directory
    defaults write "${plist}" LoadPrefsFromCustomFolder -bool true
}

setup_emacs () {
    msg_info "==> Setting up Emacs…"
    ghq get plexus/chemacs
    $(ghq list -p plexus/chemacs)/install.sh

    ghq get hlissner/doom-emacs
    $(ghq list -p hlissner/doom-emacs)/bin/doom sync
    $(ghq list -p hlissner/doom-emacs)/bin/doom doctor

    # TODO auto installing LSP
    # ELIXIR_LS_PATH=$(ghq list -p elixir-lsp/elixir-ls)/release

    ghq get syl20bnr/spacemacs
}

setup_asdf () {
    msg_info "==> Setting up global tools…"
    less asdf-plugins | xargs -n 1 asdf plugin add

    asdf install
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
    script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
    # shellcheck source=./install
    source "${script_dir}/install"
    setup_colors
    setup "$@"
fi
