#!/usr/bin/env bash

# script/setup: Set up system for the first time after cloning

set -euo pipefail
IFS=$'\n\t'

setup () {
    cd "$(dirname "$0")/.."
    script/bootstrap

    echo "==> script/setup…"
    setup_rc
    setup_secure_files
    setup_iterm
    setup_emacs
    setup_asdf
}

setup_rc () {
    echo "==> Setting up RC files…"
    local dir

    # Set this repo as the source directory.
    dir=$(pwd)
    echo "DOTFILES_DIRS=\"${dir}\"" >> ./rcrc

    # First we symbolically link just the `rcrc` file, then allow that
    # configuration to drive the default linking strategy.
    rcup -d $dir rcrc
    rcup
}

setup_secure_files () {
    echo "==> Setting up secure files…"
    local icloud_dir
    icloud_dir="${HOME}/Library/Mobile\ Documents/com\~apple\~CloudDocs"

    # symbolically link private git config
    ln -s "${icloud_dir}/gitconfig.local" ~/.gitconfig.local

    # symbolically link private zsh config
    ln -s "${icloud_dir}/rc.local" ~/.localrc
}

setup_iterm () {
    echo "==> Setting up iTerm2 preferences…"
    local dir
    local plist
    plist="com.googlecode.iterm2.plist"

    # Specify the preferences directory
    dir="$(pwd)/iTerm2"
    defaults write "${plist}" PrefsCustomFolder -string "${dir}"

    # Tell iTerm2 to use the custom preferences in the directory
    defaults write "${plist}" LoadPrefsFromCustomFolder -bool true
}

setup_emacs () {
    echo "==> Setting up Emacs…"
    ghq get plexus/chemacs
    ghq get hlissner/doom-emacs
    ghq get syl20bnr/spacemacs
    $(ghq list -p plexus/chemacs)/install.sh
}

setup_asdf () {
    echo "==> Setting up global tools…"
    asdf install
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
    setup "$@"
fi
