#!/usr/bin/env bash

# script/update: Update system for current checkout.

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
# shellcheck source=./bootstrap
source "${SCRIPT_DIR}/bootstrap"

update () {
    bootstrap
    msg_header "==> script/update…"
}

if ! (return 0 2>/dev/null); then
    update "$@"
fi
