#!/usr/bin/env bash

# script/update: Update system for current checkout.

set -euo pipefail
IFS=$'\n\t'

update () {
    cd "$(dirname "$0")/.."
    script/bootstrap
    header "==> script/update…"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
    script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
    # shellcheck source=./install
    source "${script_dir}/install"
    setup_colors
    update "$@"
fi
