[plugins.zsh-async]
github = "mafredri/zsh-async"

[plugins.promptinit]
inline = "autoload -U promptinit; promptinit"

[plugins.prompt]
github = "sindresorhus/pure"

[plugins.syntax-highlighting]
github="zdharma/fast-syntax-highlighting"

[plugins.history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.history-fzy]
gist = "shogogg/86f13a0aff12b9a31efb083946a500cb"

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.asdf]
github = "robbyrussell/oh-my-zsh"
directory = "plugins/{{ name }}"

[plugins.docker]
github = "robbyrussell/oh-my-zsh"
directory = "plugins/{{ name }}"
apply = ["fpath"]

[plugins.docker-compose]
github = "robbyrussell/oh-my-zsh"
directory = "plugins/{{ name }}"
apply = ["source", "fpath"]

# update completions
[plugins.compinit]
inline = "compinit"

# Load local plugins last, so they can overwrite config
[plugins.dotfiles]
local = "/usr/local/share/dotfiles/zsh/plugins"

